name: ArcanePerks
main: me.charixmaz.arcaneperks.ArcanePerks
version: 1.2.0
api-version: '1.21'
author: CharixMaz
description: Rank-based perk system with durations, cooldowns and LuckPerms.

commands:
  ap:
    description: ArcanePerks main command.
    usage: /ap help
    permission: arcaneperks.command.ap

  fd:
    description: Toggle Fast Digging perk.
    usage: /fd

  nv:
    description: Toggle Night Vision perk.
    usage: /nv

  strp:
    description: Toggle Strength perk.
    usage: /strp

  flyp:
    description: Toggle Fly perk.
    usage: /flyp

  kxp:
    description: Toggle Keep XP perk.
    usage: /kxp

  kinv:
    description: Toggle Keep Inventory perk.
    usage: /kinv

  nfall:
    description: Toggle No Fall Damage perk.
    usage: /nfall

  dexp:
    description: Toggle Double Exp perk.
    usage: /dexp

  ddrops:
    description: Toggle Double Mob Drops perk.
    usage: /ddrops

  godm:
    description: Toggle God perk.
    usage: /godm

  van:
    description: Toggle Vanish perk.
    usage: /van

  mig:
    description: Toggle Mobs Ignore perk.
    usage: /mig

  glow:
    description: Toggle Glowing perk.
    usage: /glow

  tele:
    description: Toggle Telekinesis perk.
    usage: /tele

  ismelt:
    description: Toggle Instant Smelt perk.
    usage: /ismelt

  spd:
    description: Toggle Speed perk.
    usage: /spd

permissions:
  arcaneperks.command.ap:
    default: op

  arcaneperks.admin.nocooldown:
    default: op
    description: Bypass perk cooldowns (for testing).
